project:
  type: website
  output-dir: docs

website:
  title: "Dr. Pablo Martín Demetrio"
  description: "Investigador Científico y Docente"
  favicon: "profile.jpg"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Inicio
      - href: investigacion.qmd
        text: Investigación
      - href: docencia.qmd
        text: Docencia
      - text: "Descargar CV"
        href: "files/CV_Pablo_Demetrio.pdf"
        target: _blank
    right:
      - icon: envelope
        href: mailto:tu-email@ejemplo.com
        aria-label: Email
      - icon: mortarboard
        href: https://scholar.google.com.ar/citations?user=XZz03X4AAAAJ&hl=es
        aria-label: Google Scholar
      - text: "CONICET"
        href: https://bicyt.conicet.gov.ar/fichas/p/pablo-martin-demetrio
        aria-label: CONICET Profile

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
