project:
  type: website
  output-dir: docs

lang: es

website:
  title: "PMD"
  description: "Investigador Científico y Docente"
  favicon: "foto_Demetrio_B&N.jpg"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Inicio
      - href: investigacion.qmd
        text: Investigación
      - href: docencia.qmd
        text: Docencia
      - href: transferencia.qmd
        text: Transferencia


    right:
      - icon: envelope
        href: mailto:pablo.demetrio@gmail.com
        aria-label: Email
      - icon: mortarboard
        href: https://scholar.google.com.ar/citations?user=XZz03X4AAAAJ&hl=es
        aria-label: Google Scholar
      - text: "<img src='conicet_logo.svg' style='height: 1.2em; vertical-align: middle; margin-right: 4px;' />"
        href: https://bicyt.conicet.gov.ar/fichas/p/pablo-martin-demetrio
        aria-label: CONICET Profile
      - text: "<img src='unlp_logo.svg' style='height: 1.6em; vertical-align: middle; margin-right: 4px;' />"
        href: https://www.fcnym.unlp.edu.ar/grado_/catedras/geoestadistica/
        aria-label: UNLP

format:
  html:
    theme:
      light: litera
      dark: slate
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
